package systemd

import (
	"path"

	util "github.com/stellaraf/rmon-node-setup/util"
)

// DockerCompose creates & sets up the AppNeta Docker Compose image as a systemd service per the docs:
// docker-compose -f mp-compose.yaml pull && docker-compose -f mp-compose.yaml up -d
func DockerCompose() {
	name := "appneta-cmp"
	service := `# This file is autogenerated. Do not override.
[Unit]
Description=AppNeta Docker Compose
Requires=docker.service
After=docker.service
StartLimitIntervalSec=0

[Service]
Type=oneshot
RemainAfterExit=true
WorkingDirectory=/etc/docker/compose
ExecStartPre=%s -f appneta-cmp.yaml pull
ExecStart=%s -f appneta-cmp.yaml up -d --remove-orphans

[Install]
WantedBy=multi-user.target
`
	user := util.CurrentUser()
	bin := path.Join(user.HomeDir, "/.local/bin/docker-compose")
	if user.Name == "root" {
		bin = "/usr/local/bin/docker-compose"
	}
	r := Root()
	r.WriteSystemd(name, service, bin, bin)
	r.ReloadServices()
	r.EnableService(name)
	r.StartService(name)
}
